server:
  port: 8080
spring:
  datasource:
    name: mybatis-plus-test
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis-plus-test?serverTimezone=GMT%2B8
    password: issyu153
    username: root
