server:
  port: 8088
spring:
  datasource:
    name: mall
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=GMT%2B8
    username: root
    password: issyu153
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

